name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Set up Python 🧰
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: 3.x

      - name: Install dependencies 🧰
        env:
          PIP_ROOT_USER_ACTION: ignore
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package 🔨
        run: python -m build

      - name: Publish package 🚀
        uses: Commandcracker/pypi-publish@8d13f542c4bb425036897e69001b670654c41a8d
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
